name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        id: test
        run: npm test

      - name: Run ESLint
        id: lint
        run: npm run lint
