name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        id: test
        run: npm test

      - name: Run ESLint
        id: lint
        run: npm run lint

  Deploy:
    needs: [Jest]
    runs-on: ubuntu-latest
    if: ${{ needs.Jest.result == 'success' && needs.lint.result == 'success' }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Push to Master
        run: |
          git checkout master
          git push origin master
